openapi: "3.0"
info:
  title: Yandex IAM API
  description: This API reference is organized by resource. Actions are performed
    by sending HTTP requests to resource URLs or making RPC calls. For more information
    about Yandex.Cloud API architecture, see [API Concepts](/docs/api-design-guide/).
  version: v1
  x-y-docUri: api-ref
  x-y-baseUrl: https://iam.api.cloud.yandex.net
paths:
  /iam/aws-compatibility/v1/accessKeys:
    get:
      tags:
      - AccessKey
      summary: Retrieves the list of access keys for the specified service account.
      operationId: AccessKeyList
      parameters:
      - name: serviceAccountId
        in: query
        description: |-
          ID of the service account to list access keys for.
          To get the service account ID, use a [list](/docs/iam/api-ref/ServiceAccount/list) request.
          If not specified, it defaults to the subject that made the request.

          The maximum string length in characters is 50.
        schema:
          type: string
      - name: pageSize
        in: query
        description: |-
          The maximum number of results per page to return. If the number of available
          results is larger than [pageSize](/docs/iam/api-ref/AccessKey/list#query_params),
          the service returns a [nextPageToken](/docs/iam/api-ref/AccessKey/list#responses)
          that can be used to get the next page of results in subsequent list requests.
          Default value: 100.

          The maximum value is 1000.
        schema:
          type: string
          format: int64
      - name: pageToken
        in: query
        description: |-
          Page token. To get the next page of results, set [pageToken](/docs/iam/api-ref/AccessKey/list#query_params)
          to the [nextPageToken](/docs/iam/api-ref/AccessKey/list#responses)
          returned by a previous list request.

          The maximum string length in characters is 100.
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListAccessKeysResponse'
      x-y-navtitle: list
    post:
      tags:
      - AccessKey
      summary: Creates an access key for the specified service account.
      operationId: AccessKeyCreate
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateAccessKeyRequest'
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateAccessKeyResponse'
      x-y-navtitle: create
  /iam/aws-compatibility/v1/accessKeys/{accessKeyId}:
    get:
      tags:
      - AccessKey
      summary: Returns the specified access key.
      description: To get the list of available access keys, make a [list](/docs/iam/api-ref/AccessKey/list)
        request.
      operationId: AccessKeyGet
      parameters:
      - name: accessKeyId
        in: path
        description: |-
          Required.
          ID of the AccessKey resource to return.
          To get the access key ID, use a [list](/docs/iam/api-ref/AccessKey/list) request.

          The maximum string length in characters is 50.
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccessKey'
      x-y-navtitle: get
    delete:
      tags:
      - AccessKey
      summary: Deletes the specified access key.
      operationId: AccessKeyDelete
      parameters:
      - name: accessKeyId
        in: path
        description: |-
          Required.
          ID of the access key to delete.
          To get the access key ID, use a [list](/docs/iam/api-ref/AccessKey/list) request.

          The maximum string length in characters is 50.
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Empty'
      x-y-navtitle: delete
components:
  schemas:
    AccessKey:
      description: |-
        An access key.
        For more information, see [AWS-compatible access keys](/docs/iam/concepts/authorization/access-key).
      type: object
      properties:
        id:
          description: |-
            ID of the AccessKey resource.
            It is used to manage secret credentials: an access key ID and a secret access key.
          type: string
        serviceAccountId:
          description: ID of the service account that the access key belongs to.
          type: string
        createdAt:
          description: |-
            Creation timestamp.

            String in [RFC3339](https://www.ietf.org/rfc/rfc3339.txt) text format.
          type: string
          format: date-time
        description:
          description: Description of the access key. 0-256 characters long.
          type: string
        keyId:
          description: |-
            ID of the access key.
            The key is AWS compatible.
          type: string
    CreateAccessKeyRequest:
      type: object
      properties:
        serviceAccountId:
          description: |-
            ID of the service account to create an access key for.
            To get the service account ID, use a [list](/docs/iam/api-ref/ServiceAccount/list) request.
            If not specified, it defaults to the subject that made the request.

            The maximum string length in characters is 50.
          type: string
        description:
          description: |-
            Description of the access key.

            The maximum string length in characters is 256.
          type: string
    CreateAccessKeyResponse:
      type: object
      properties:
        accessKey:
          $ref: '#/components/schemas/AccessKey_in_CreateAccessKeyResponse_accessKey'
        secret:
          description: |-
            Secret access key.
            The key is AWS compatible.
          type: string
    Empty:
      description: Empty JSON object `` {} ``.
      type: object
      maxProperties: 0
    ListAccessKeysResponse:
      type: object
      properties:
        accessKeys:
          description: List of access keys.
          type: array
          items:
            $ref: '#/components/schemas/AccessKey'
        nextPageToken:
          description: |-
            This token allows you to get the next page of results for list requests. If the number of results
            is larger than [pageSize](/docs/iam/api-ref/AccessKey/list#query_params), use
            the [nextPageToken](/docs/iam/api-ref/AccessKey/list#responses) as the value
            for the [pageToken](/docs/iam/api-ref/AccessKey/list#query_params) query parameter
            in the next list request. Each subsequent list request will have its own
            [nextPageToken](/docs/iam/api-ref/AccessKey/list#responses) to continue paging through the results.
          type: string
    AccessKey_in_CreateAccessKeyResponse_accessKey:
      description: |-
        AccessKey resource.

        An access key.
        For more information, see [AWS-compatible access keys](/docs/iam/concepts/authorization/access-key).
      type: object
      properties:
        id:
          description: |-
            ID of the AccessKey resource.
            It is used to manage secret credentials: an access key ID and a secret access key.
          type: string
        serviceAccountId:
          description: ID of the service account that the access key belongs to.
          type: string
        createdAt:
          description: |-
            Creation timestamp.

            String in [RFC3339](https://www.ietf.org/rfc/rfc3339.txt) text format.
          type: string
          format: date-time
        description:
          description: Description of the access key. 0-256 characters long.
          type: string
        keyId:
          description: |-
            ID of the access key.
            The key is AWS compatible.
          type: string
tags:
- name: AccessKey
  description: A set of methods for managing access keys.
